(function() {if(!window.keyman.ui.name)try{var a=window.keyman,k=a.osk,m=a.util;if(m.isTouchDevice())throw"";a.ui={C:!1,c:null,Na:null,v:null,w:null,X:null,F:null,ha:null,i:null,R:null,u:null,m:[],l:null,W:[],D:[],j:"as",b:[],fa:0,Da:1,Ba:null,A:null,G:"",za:0,Aa:0,languages:[],M:!1,I:0,P:""};var n=a.ui;n.name="toolbar";n.a={oa:"Languages",ra:"Turn off KeymanWeb keyboards",qa:"Off",ua:"Show On Screen Keyboard",pa:"Select language"};n.a.SelectKeyboardPre="Select ";n.a.SelectKeyboardSuf="keyboard";n.a.AltKeyboardsPre=
"Alternate keyboards for ";n.a.AltKeyboardsSuf="";n.a.ca="Central America";n.a.sa="South America";n.a.na="North America";n.a.eu="Europe";n.a.af="Africa";n.a.me="Middle east";n.a.as="Asia";n.a.oc="Oceania";n.createNode=function(c,b,d,e){var f=document.createElement(c);b&&(f.id=b);d&&(f.className=d);e&&(f.innerHTML=e);if("a"==c||"area"==c||"map"==c)f.Ra=function(){return!1};return f};n.initialize=n.Pa=function(){if(a.initialized&&!n.C){var c=document.getElementById("KeymanWebControl");if(!c){if(null==
document.body)return;c=document.createElement("DIV");c.id="KeymanWebControl";document.body.insertBefore(c,document.body.firstChild);n.va=c}c.style.visibility="hidden";c.style.maxHeight="35px";n.C=!0;if(!m.isTouchDevice()){m.linkStyleSheet(m.getOption("resources")+"ui/toolbar/kmwuitoolbar.css");n.g={};n.g.ca={t:n.a.ca,o:"49,52,65,54,68,57,71,56,73,59,75,60,93,61,94,58,97,58,101,59,107,60,114,64,115,68,114,77,104,74,98,75,96,78,95,82,90,81,85,80,82,76,78,74,74,73,65,68,57,61"};n.g.sa={t:n.a.sa,o:"82,82,95,82,96,78,98,75,104,74,114,77,120,79,124,83,126,87,141,90,142,97,138,103,135,113,127,116,123,124,115,131,112,132,109,138,117,139,140,141,141,146,134,148,114,145,109,148,100,148,91,143,91,130,96,111,89,102,83,95,77,89"};
n.g.na={t:n.a.na,o:"0,3,0,37,24,32,35,37,43,47,49,52,65,54,68,57,71,56,73,59,75,60,93,61,93,57,103,49,118,41,126,41,136,23,148,17,156,14,164,5,164,0,57,0,35,5,25,9,5,8"};n.g.eu={t:n.a.eu,o:"145,29,146,19,158,14,171,6,187,2,206,1,217,4,227,11,231,16,231,33,227,34,225,35,225,37,227,39,228,44,228,47,227,48,223,46,218,44,215,43,208,43,203,45,202,48,205,52,201,52,195,49,189,50,187,48,177,48,175,49,166,50,147,33"};n.g.af={t:n.a.af,o:"150,58,158,50,166,50,175,49,177,48,187,48,189,50,195,49,201,52,205,52,207,53,221,75,229,75,231,77,231,85,227,92,232,101,237,106,237,112,227,115,222,118,206,125,199,127,193,127,185,111,183,104,180,87,168,89,153,85,143,71,147,60"};
n.g.me={t:n.a.me,o:"205,52,202,48,203,45,208,43,215,43,218,44,223,46,227,48,232,48,239,48,240,49,239,53,242,60,243,65,237,76,231,77,229,75,221,75,207,53"};n.g.as={t:n.a.as,o:"219,1,221,6,228,12,231,16,231,33,227,34,225,35,225,37,227,39,229,45,232,48,239,48,240,49,239,53,242,60,243,65,249,70,252,81,259,87,271,87,278,95,289,100,303,101,311,98,320,98,323,98,323,84,311,81,308,73,307,65,317,57,330,50,334,44,348,36,364,38,375,34,375,8,355,8,336,5,292,1,285,0,219,0"};n.g.oc={t:n.a.oc,o:"288,117,289,107,303,101,311,98,323,98,323,84,333,77,344,73,362,80,369,88,375,96,375,141,352,143,323,142,316,136,310,130,291,130"};
n.c=n.createNode("div","kmw_controls");n.c.style.display="block";var b=n.createNode("a","kmw_controls_start",null," ");b.href="https://keyman.com/developer/keymanweb/";b.target="_blank";n.c.appendChild(b);n.w=n.createNode("div","kmw_btn_keyboards","kmw_button");n.w.title=n.a.pa;b=n.createNode("a",null,"kmw_button_a");b.href="#";b.onclick=n.Ka;b.appendChild(n.createNode("div","kmw_img_keyboards","kmw_img"));b.appendChild(n.createNode("div",null,"kmw_a",n.a.oa));b.appendChild(n.createNode("div",null,
"kmw_drop"));n.w.appendChild(b);n.u=n.createNode("div","kmw_selector");n.s=n.createNode("div","kmw_selector_regions");n.v=n.createNode("div","kmw_browsemap");b=n.createNode("img","kmw_region_browsemap");b.src=m.getOption("resources")+"ui/toolbar/blank.gif";b.useMap="#kmw_worldgrey16";n.v.appendChild(b);var d=n.createNode("map","kmw_worldgrey16");d.name="kmw_worldgrey16";for(var e in n.g)b=n.createNode("area"),b.shape="poly",b.alt="",b.href="#",b.title=n.g[e].t,b.Oa="true",b.onclick=function(b){return function(c){return n.Z(c,
b)}}(e),b.onmouseover=function(b){return function(c){return n.ea(c,b)}}(e),b.onmouseout=function(b){return function(c){return n.ka(c,b)}}(e),b.coords=n.g[e].o,d.appendChild(b);b=n.createNode("area");b.shape="default";b.Qa="true";b.alt="";b.onclick=n.h;d.appendChild(b);n.v.appendChild(d);n.s.appendChild(n.v);n.l={};b=n.createNode("ul");for(e in n.g)d=n.createNode("li"),n.l[e]=n.createNode("a",null,null,n.g[e].t),n.l[e].href="#",n.l[e].onclick=function(b){return function(c){return n.Z(c,b)}}(e),n.l[e].onmouseover=
function(b){return function(c){return n.ea(c,b)}}(e),n.l[e].onmouseout=function(b){return function(c){return n.ka(c,b)}}(e),d.appendChild(n.l[e]),b.appendChild(d);n.s.appendChild(b);n.u.appendChild(n.s);n.w.appendChild(n.u);n.c.appendChild(n.w);n.c.appendChild(n.ha=n.createNode("div","kmw_bar_off","kmw_bar"));n.F=n.createNode("div","kmw_btn_off","kmw_button_selected");b=n.createNode("a",null,"kmw_button_a");b.href="#";b.onclick=n.Ea;b.title=n.a.ra;b.appendChild(n.createNode("div","kmw_img_off","kmw_img"));
b.appendChild(n.createNode("div",null,"kmw_a",n.a.qa));n.F.appendChild(b);n.c.appendChild(n.F);n.c.appendChild(n.X=n.createNode("div","kmw_control_keyboards","kmw_button"));n.c.appendChild(n.R=n.createNode("div","kmw_bar_osk","kmw_bar"));n.i=n.createNode("div","kmw_btn_osk","kmw_button");b=n.createNode("a",null,"kmw_button_a");b.href="#";b.onclick=n.La;b.title=n.a.ua;b.appendChild(n.createNode("div","kmw_img_osk","kmw_img"));n.i.appendChild(b);n.c.appendChild(n.i);n.c.appendChild(n.createNode("div",
"kmw_controls_end",null," "));e=n.createNode("div");e.id="kmw_map_preload";n.c.appendChild(e);n.c.appendChild(n.createNode("br",null,"kmw_clear"));c.appendChild(n.c);n.M=!0;n.I&&clearTimeout(n.I);n.I=setTimeout(n.N,2E3);m.attachDOMEvent(document.body,"click",n.da,!1);n.j="eu";a.focusLastActiveElement()}}};n.Sa=function(){var c=n.c;c&&c.parentNode.removeChild(c);(c=n.va)&&c.parentNode.removeChild(c)};n.N=function(){if(n.M){n.M=!1;var c=0;n.m={};var b=a.getKeyboards();b.sort(n.Ma);for(c=n.s.childNodes.length;0<
c;c--)"kmw_selector_region"==n.s.childNodes[c-1].className&&n.s.removeChild(n.s.childNodes[c-1]);for(var d in n.g){n.m[d]=n.createNode("div",null,"kmw_selector_region");for(var e=n.createNode("div",null,"kmw_keyboard_col"),f=0,g=0,l="",h=0;h<b.length;h++)b[h].RegionCode==d&&b[h].LanguageCode!=l&&(l=b[h].LanguageCode,f++);f=Number(((f+3)/4).toFixed(0));l="";for(h=0;h<b.length;h++)if(b[h].RegionCode==d)if(b[h].LanguageCode==l){var p=n.languages[l].f;p.push?p.push(b[h]):n.languages[l].f=p.concat(b[h])}else{l=
b[h].LanguageCode;n.languages[l]={id:b[h].LanguageCode,name:b[h].LanguageName,f:[b[h]]};0==g%f&&0<g&&(n.m[d].appendChild(e),e=n.createNode("div",null,3==g/f?"kmw_keyboard_col_right":"kmw_keyboard_col"));g++;p=n.createNode("div",null,"kmw_language");var q=n.createNode("a",null,null,b[h].LanguageName);q.href="#";q.onclick=function(b){return function(c){return n.ja(c,b)}}(n.languages[l]);p.appendChild(q);e.appendChild(p);c++}n.m[d].appendChild(e);n.m[d].appendChild(n.createNode("div",null,"kmw_clear"));
n.s.appendChild(n.m[d])}n.Ca();n.Z(null,n.j);n.U();a.focusLastActiveElement()}};n.Ma=function(c,b){return c.RegionCode<b.RegionCode?-2:c.RegionCode>b.RegionCode?2:c.LanguageName<b.LanguageName?-1:c.LanguageName>b.LanguageName?1:0};n.J=function(c){for(var b=0;b<n.b.length;b++)if(n.b[b].lang.id==c.id)return b;return null};n.ba=function(c,b){var d=n.J(c);if(null==d){if(n.b.length>=n.Da){var e=2147483647;d=null;for(var f=0;f<n.b.length;f++)n.b[f].Y<e&&(d=f,e=n.b[f].Y);null!=d&&(e=n.b[d],n.D[e.lang.id]=
null,n.W[e.lang.id]=null,n.X.removeChild(e.O),n.b=0==d?n.b.slice(d+1):d==n.b.length-1?n.b.slice(0,d):n.b.slice(0,d).concat(n.b.slice(d+1)))}d=n.createNode("div",null,"kmw_button");e=n.createNode("a",null,"kmw_button_a"+(1<c.f.length?" kmw_norightgap":""));e.href="#";f=n.a.SelectKeyboardPre+b.Name;var g=n.a.SelectKeyboardSuf;0>f.toLowerCase().indexOf(g.toLowerCase())&&(f=f+" "+g);e.title=f;e.onclick=function(b){return n.ja(b,c)};e.appendChild(n.createNode("div","kmw_img_kbd","kmw_img"));n.P=n.truncate(c.name,
28);e.appendChild(n.createNode("div",null,"kmw_a",n.P));d.appendChild(e);g=e;if(1<c.f.length){e=n.createNode("a",null,"kmw_button_a kmw_noleftgap");e.href="#";e.title=n.a.AltKeyboardsPre+c.name+n.a.AltKeyboardsSuf;e.onclick=function(b){return n.Ja(b,c)};var l=n.createNode("div",null,"kmw_a");f=n.truncate(b.Name.replace(/\s?keyboard/i,""),40-n.P.length);l.appendChild(n.W[c.id]=n.createNode("span",null,"kmw_kbd",f));e.appendChild(l);e.appendChild(n.createNode("div",null,"kmw_drop"));d.appendChild(e);
n.D[c.id]=n.createNode("ul",null,"kmw_selector_kbd");n.D[c.id].style.display="none";for(var h in c.f)l=n.createNode("li"),f=c.f[h].Name.replace(/\s?keyboard/i,""),e=n.createNode("a",null,null,f),e.href="#",e.title="",e.onclick=function(b,c){return function(d){return n.L(d,b,c)}}(c,c.f[h]),l.appendChild(e),n.D[c.id].appendChild(l);d.appendChild(n.D[c.id])}n.X.appendChild(d);n.b.push({Y:n.fa++,lang:c,V:b,O:d,aa:g})}else{n.b[d].Y=n.fa++;n.b[d].V=b;if(h=n.W[c.id])f=b.Name.replace(/\s?keyboard/i,""),h.innerHTML=
n.truncate(f,40-n.P.length);n.b[d].aa&&(f=n.a.SelectKeyboardPre+b.Name,g=n.a.SelectKeyboardSuf,0>f.toLowerCase().indexOf(g.toLowerCase())&&(f=f+" "+g),n.b[d].aa.title=f)}};n.truncate=function(c,b){return c.length<=b?c:c.substr(0,b-1)+"\u2026"};n.Ia=function(){n.M=!0;n.I&&clearTimeout(n.I);n.I=setTimeout(n.N,2E3)};a.addEventListener("keyboardregistered",n.Ia);n.B=function(c){var b=n.ga;b&&(b.style.display="none");n.S();return n.h(c)};n.Ja=function(c,b){n.K(c);if(b=n.D[b.id]){if("block"==b.style.display)return n.B(c);
b.style.display="block";n.ga=b;n.$(b,n.B)}return n.h(c)};n.ja=function(c,b){var d=n.J(b);return(d=null==d?b.f[0]:n.b[d].V)?n.L(c,b,d):!1};n.L=function(c,b,d){if(n.G){var e=n.J(n.G);null!=e&&(n.b[e].O.className="kmw_button")}n.F.className="kmw_button";n.G=b;n.A=d;n.ta=b.id;n.H();n.ba(b,d);a.setActiveKeyboard(d.InternalName,b.id);n.b[n.J(b)].O.className="kmw_button_selected";n.ia();n.U();return n.K(c)||n.B(c)};n.U=function(){var c=[n.F,n.ha,n.i,n.R],b=!1;a.isCJK(n.A)?b=!0:null==n.A&&(b="none"==c[2].style.display);
if(null!=n.A||0<n.b.length)for(var d=0;d<c.length;d++)c[d].style.display="";else for(d=0;d<c.length;d++)c[d].style.display="none";b?n.i.style.display=n.R.style.display="none":null==n.A&&(n.i.className="kmw_button_disabled");n.c.parentNode.style.visibility="visible"};n.H=function(){a.focusLastActiveElement()};n.La=function(c){k&&""!=a.getActiveKeyboard()&&(k.isEnabled()?k.hide():k.show(!0));n.H();return n.h(c)};n.Ea=function(c){if("kmw_controls_disabled"!=n.c.className){n.B(null);if(n.G){var b=n.J(n.G);
null!=b&&(n.b[b].O.className="kmw_button")}n.A=null;n.G=null;n.ta="";n.F.className="kmw_button_selected"}n.H();a.setActiveKeyboard("","");n.ia();n.U();return n.h(c)};n.h=function(c){c||(c=window.event);window.event&&(window.event.returnValue=!1);c&&(c.cancelBubble=!0);return!1};n.Z=function(c,b){var d=n.v;if(!d)return n.h(c);d.className="kmw_browsemap_"+b;"undefined"==typeof n.m[b]&&(n.M=!0,n.N());n.m[b].style.display="block";n.l[b].className="selected";null!=n.j&&n.j!=b&&(n.m[n.j].style.display=
"none",n.l[n.j].className="");n.j=b;return n.h(c)};n.ka=function(c,b){n.v.className=null==n.j?"":"kmw_browsemap_"+n.j;n.l[b].className=n.j==b?"selected":"";return n.h(c)};n.ea=function(c,b){n.v.className="kmw_browsemap_"+b+"_sel";n.l[b].className="hover";return n.h(c)};n.Ha=function(c){return c.getAttribute?c.getAttribute("kmw_disable")||c.kmw_disable:c.kmw_disable};n.ya=function(c){if(!n.C)return!0;c=c.target;if("textarea"==c.tagName.toLowerCase()||"input"==c.tagName.toLowerCase()&&"text"==c.type.toLowerCase())if(n.Ba=
c,n.Ha(c))"kmw_controls_disabled"!=n.c.className&&(n.c.className="kmw_controls_disabled");else{null!=n.A&&(a.isCJK()?n.i.style.display=n.R.style.display="none":n.i.className=k&&k.isEnabled()?"kmw_button_selected":"kmw_button");""!=n.c.className&&(n.c.className="");var b=c.la?c.la:64;var d=c.ma?c.ma:0;n.za=m.getAbsoluteX(c)+b;n.Aa=m.getAbsoluteY(c)+c.offsetHeight+d}return!0};a.addEventListener("controlfocused",n.ya);n.wa=function(){if(!n.C)return!0;"none"!=n.i.style.display&&(n.i.className="kmw_button_disabled");
return!0};a.addEventListener("controlblurred",n.wa);n.xa=function(c){var b=c.internalName;c=c.languageCode;if(""!=c&&""!=b&&(c=n.languages[c],null!=c))for(var d=0;d<c.f.length;d++)c.f[d].InternalName==b&&(n.L(null,c,c.f[d]),window.focus(),n.H());return!0};a.addEventListener("keyboardchange",n.xa);n.Ga=function(c){n.C&&(n.i.className="kmw_button_selected");return c};k.addEventListener("show",n.Ga);n.Fa=function(c){n.C&&c.HiddenByUser&&(n.i.className="kmw_button")};k.addEventListener("hide",n.Fa);n.Ka=
function(c){n.N();if("kmw_controls_disabled"==n.c.className)return n.h(c);n.B(null);if("kmw_over"==n.u.className)return n.K(c);n.u.className="kmw_over";n.w.className="kmw_button_selected";n.$(n.u,n.K);return n.h(c)};n.K=function(c){n.u.className="";n.w.className="kmw_button";n.S();return n.h(c)};n.da=function(c){var b=n.ga;if((!b||"none"==b.style.display)&&""==n.u.className)return!0;n.K(c);n.B(c);return n.h(c)};var r=null,t=null,u=null;n.T=function(c){var b=c&&c.target||window.event&&window.event.srcElement;
if(b)for(;b.parentNode;){if(b==t)return null;b=b.parentNode}"#document"==b.nodeName&&n.da(c);return r};n.$=function(c,b){n.T==document.onclick&&n.S();r=b;t=c;u=document.onclick;document.onclick=n.T};n.S=function(){n.T==document.onclick&&(document.onclick=u,t=r=u=null)};n.Ca=function(){var c="",b=m.loadCookie("KeymanWeb_Keyboard");void 0!=b.current&&(c=b.current.split(":")[0]);b=m.loadCookie("KeymanWeb_Toolbar");void 0!=b.region&&(n.j=b.region);if(void 0!=b.maxrecent)for(var d=0;d<b.maxrecent;d++){if(void 0!=
b["recent"+d]){var e=b["recent"+d].split(",");if(2==e.length){var f=n.languages[e[0]];if(null!=f)for(var g=0;g<f.f.length;g++)if(f.f[g].InternalName==e[1]){n.ba(f,f.f[g]);if(f.f[g].InternalName==c){n.L(null,f,f.f[g]);window.focus();n.H();break}break}}}}else if(c=a.getActiveKeyboard(),g=a.getActiveLanguage(),""!=g&&""!=c&&(b=n.languages[g],null!=b))for(g=0;g<b.f.length;g++)b.f[g].InternalName==c&&(n.L(null,b,b.f[g]),window.focus(),n.H())};n.ia=function(){var c={};c.region=n.j;c.maxrecent=""+n.b.length;
for(var b=0;b<n.b.length;b++)c["recent"+b]=n.b[b].lang.id+","+n.b[b].V.InternalName;m.saveCookie("KeymanWeb_Toolbar",c)}}catch(c){};}());
//# sourceMappingURL=kmwuitoolbar.js.map
